runtime: go115
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
  max_pending_latency: 15s
  min_pending_latency: 15s

default_expiration: "10m"

env_variables:
  GOT_PROJECT_ID: "got-slothninja-games"
  GOT_HOST_URL: "got.slothninja.com"
  GOT_DS_URL: "got.slothninja.com"
  USER_PROJECT_ID: "user-slothninja-games"
  USER_DS_URL: "user.slothninja.com"
  USER_HOST_URL: "https://user.slothninja.com"
  NODE_ENV: "production"
  MJ_API_KEY_PUB: "0b66e3cf5d4b5a5c536ef1a289b58d79"
  MJ_API_KEY_PRIV: "e4ba83076c32f4732e84a1b05cb4e3e5"

handlers:
- url: /img
  static_dir: dist/img
  secure: always

- url: /js
  static_dir: dist/js
  secure: always

- url: /css
  static_dir: dist/css
  secure: always

- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /index.html
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /(.*\.(gif|png|jpg|js|ico|txt|html|json))$
  static_files: dist/\1
  upload: dist/.*\.(gif|png|jpg|js|ico|txt|html|json)$
  secure: always

- url: /.*
  script: auto
  secure: always
